name: Publish Release

on:
  push:
    branches: [ master ]
    tags: [ v*.*.* ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NODE_VERSION: '16.x'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: npm install, build, and test
        run: |
          npm ci
          npm run build --if-present
          npm run test --if-present
      
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.12
        with:
          files: |
            build/*
            package.json
            package-lock.json
